### ISSUE TITLE
Support for django 1.8/1.9?

### ISSUE THREAD

**Issue by reiven** [duosecurity/duo_python#12]
Hi! I just want to know if you plan to release a duo_python compatible with latests django versions? 

Thanks

**Comment by mschwager** [comment]
Hey @reiven! By compatible do you mean update our demo (https://github.com/duosecurity/duo_python/tree/master/demos/django), or is there some fundamental Python incompatibility?

Also, we're open to pull requests if you'd like to submit one :)

**Comment by surferbrend** [comment]
Hey @mschwager, I am having difficulties using this demo in django 1.9. I have no problem using django 1.7 but I really want it in 1.9. The urls.py and views.py are not communicating.

Thanks for the help

**Comment by jcmedinaq** [comment]
Hi there! same question here. Changes in Django 1.9 prevent the current demo from running. Is there an update for the demo in the near future you guys are planning on delivering?

Thanks!

**Comment by DuoKristina** [comment]
We'll take a look soon. Thanks for your valuable feedback, and for using Duo!

**Comment by applebull** [comment]
In Django 1.9, this demo could not run at all. I would be appreciate if someone could solve this issue.

**Comment by echolabstech** [comment]
Upgrades to 1.9 and 1.10 are in development, and should be available soon. Thanks for using Duo, cheers!

**Comment by echolabstech** [comment]
@applebull @jcmedinaq @reiven Django is now updated to 1.10
