### ISSUE TITLE
STATIC_PREFIX variable name is non-consistent and over-generalized

### ISSUE THREAD

**Issue by IlyaSemenov** [duosecurity/duo_python#2]
Look at the typical setup in settings.py:
```python
DUO_ENABLED = True
DUO_IKEY = 'blah'
DUO_SKEY = 'blah-blah'
DUO_HOST = 'api-blah.duosecurity.com'
STATIC_PREFIX = 'http://static.blah.com/duo'
```
The first four variables are well named and self-describing. The last one is clearly poorly named and doesn't keep any relation with Duo Auth in its name. The naming is over-generalized (a static prefix of *everything?*) and thus imposes the risk of clashing with some other application's variable sooner or later. It is also very similar to Django's STATIC_URL, which brings unnecessary confusion.

Also, Django's STATIC_URL is supposed to include the trailing /, and duo_python's STATIC_PREFIX is supposed to **not** include the trailing /. Another unreasonable inconsistency.

What I suggest is that you change the variable name to DUO_STATIC_URL (which resembles Django naming and meaning but adds the distinguishing prefix). If that variable is not present in settings.py, duo_python should revert to the old format and use STATIC_PREFIX, to ensure backward compatibility.

**Comment by mschwager** [comment]
Looks like 3bcf55090903a0ddcef2a9f94a75f156e5126098 fixed this issue. Thanks for the suggestions, though!
