### ISSUE TITLE
Prevent possible timing analysis?

### ISSUE THREAD

**Issue by script3r** [duosecurity/duo_python#22]
https://github.com/duosecurity/duo_python/blob/d5ca19092cbc7dcfc7dfcfe517fc4e3c2690c5f4/duo_web/__init__.py#L58

Would the call above be further protected by making use of methods such as `[compare_digest](https://docs.python.org/2/library/hmac.html#hmac.compare_digest)`?

**Comment by adrikim** [comment]
Not in particular. We've already essentially implemented double HMAC verification here to mitigate timing attacks (see [here](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/) for more info). `hmac.compare_digest` is an alternative to what's already there, but it would also require a slightly newer version of Python as well.

Thanks for the inquiry! I'll close this for now, but feel free to re-open if you have any other questions or concerns. :)
