### ISSUE TITLE
Does not show how to ensure 2FA is enabled for admin panel

### ISSUE THREAD

**Issue by hangtwenty** [duosecurity/duo_python#24]
In Django you'd have another step to enable 2FA for login through the admin panel. I think the example should demonstrate this in Python (ideally), **and** a note in the README to emphasize it. Else, at least a note in the README.

Before submitting a pull request, I figured I'd ask if there is a reason to omit this - I could be missing something! What do you think? Thanks!

**Comment by hangtwenty** [comment]
Ping... this seems like an important issue to me

**Comment by xdesai** [comment]
Hi @hangtwenty,
Thanks for you interest in securing Django with Duo. There is no specific reason that this isn't included right now. The purpose of these demo examples was just to provide some ideas on how to get started. It was not intended to be a fully comprehensive example on how to secure a site. This is likely why the admin panel piece was not included. We'd definitely be interested in seeing a pull request or a fork of this repository and we'll do our best to see if it can be merged in.

Sorry for the delay in our response to you and thanks for using Duo!
- Xander

**Comment by hangtwenty** [comment]
Great. I have just added to the README, I think this should cover it - any approach taken in the code sample would be a bit 'opinionated' and wouldn't fit all users. So this seems to work. What do you think?

**Comment by xdesai** [comment]
Closed by #25
