### ISSUE TITLE
higher versions of Django cause errors

### ISSUE THREAD

**Issue by chrivand** [duosecurity/duo_python#35]
Make sure that you Django version is 2.0.2, or if you prefer to use a higher version, then you need to be aware that the Login View has changed, and therefore some code alterations are needed (otherwise you will get error of missing positional argument "user"). Currently the requirements.txt does not state a specific Django version.

More info here: https://stackoverflow.com/questions/47801453/getting-this-error-in-django-login-missing-1-required-positional-argument-u

**Comment by lgreerduo** [comment]
Hi chrivand, 

Thank you for the heads up! I do apologize for the lengthy response time. The django version has been called out now with the latest python2 supported version, 1.11.27, as 2.0.2 is EoL at this point.
