### ISSUE TITLE
ModuleNotFoundError: No module named 'duo_app'

### ISSUE THREAD

**Issue by heckyeahcool** [duosecurity/duo_python#37]
Having trouble getting this to work with a higher version of django, six, and python. Any chance this is still a supported project?

I was intending to integrate 'duo_python' aka `pip install duo_web`(https://github.com/duosecurity/duo_python), to our local CAS server environment(django-mama-cas: https://github.com/jbittel/django-mama-cas) for 2FA to our local webapps. When I run the command `python manage.py makemigration`, I get the error below. Am I missing something in setup? I've followed the examples at https://github.com/duosecurity/duo_python/tree/master/demos/django and I do see that I am on newer versions of 'django', 'six' and even 'Python'. Any ideas what I can try? Is this project still active? Thanks in Advance!

"""
python manage.py makemigration
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/n/fs/test/cas_container/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/n/fs/test/cas_container/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/n/fs/test/cas_container/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/n/fs/test/cas_container/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/n/fs/test/cas_container/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/n/fs/test/cas_container/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'duo_app'

"""

# Settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mama_cas',
    'duo_app',
]

# pip list

Package          Version  
---------------- ---------
certifi          2019.9.11
chardet          3.0.4    
Django           2.2.6    
django-auth-ldap 2.0.0    
django-mama-cas  2.4.0    
django-pam       1.6.0    
duo-web          1.3.0    
idna             2.8      
mysqlclient      1.4.4    
pip              20.0.2  
pyasn1           0.4.7    
pyasn1-modules   0.2.7    
python-ldap      3.2.0    
python-pam       1.8.4    
pytz             2019.3  
requests         2.22.0  
setuptools       45.1.0  
six              1.12.0  
sqlparse         0.3.0    
urllib3          1.25.6  
wheel            0.34.0

**Comment by xdesai** [comment]
Hey Brian,
Thanks for checking out duo_python repo and working to build an integration. I'm sorry you're having some trouble, but hopefully we can get you on the right path.

One thing that sticks out to me about your stack trace is that it appears you are trying to import `duo_app`.
`duo_app` is actually just a module that we provided for our django example. So when you install our project via `pip install duo_web` you won't actually get the module `duo_app`. The module you do get is `duo_web`
If you take a look at our django example you'll see that duo_app just provides some hooks for the login functionality of our sample app and then uses duo_web to perform the 2fa. What I would suggest for you is to
1. Assess whether you actually need to be using duo_app directly. Maybe your CAS server already has some login handlers etc and you can edit those to use duo_web.
2. If you do end up concluding that using the duo_app module directly is what you need then you'll have to download that folder directly and put it into your project. We don't provide it via a pip install.

I hope this helps. Please let us know if you have any other issues or questions!

**Comment by heckyeahcool** [comment]
@xdesai Thanks for the reply. I guess I'm confused in general about what this module does and how to set it up. Is this module simply for adding duo to a python webapp, or can I integrate it into a CAS server as an added layer without writing custom code?  Also, what is the difference between this module and duo_client_python?

**Comment by xdesai** [comment]
I would imagine in most cases if you are going to use this package you'll probably need to write at least some amount of custom code.
If it helps you can think of the examples in the `demo` folder as showing an example of the custom code that would need to be written to add Duo to your web app.
duo_client_python is a library specifically for providing access to our rest APIs. Here's some docs about our [auth api](https://duo.com/docs/authapi) and [admin api](https://duo.com/docs/adminapi).
duo_python on the other hand is what you would use to add the Duo Prompt to your web applications see [Duo Web](https://duo.com/docs/duoweb)

**Comment by xdesai** [comment]
I'm gonna go ahead and close out this issue now. If you do have any more questions or issues please do reach back out.
Best of luck!
-Xander
