### ISSUE TITLE
FUTURE_RESPONSE in the unit tests is not in the future anymore 

### ISSUE THREAD

**Issue by vlstv** [duosecurity/duo_python#53]
`FUTURE_RESPONSE = "AUTH|dGVzdHVzZXJ8RElYWFhYWFhYWFhYWFhYWFhYWFh8MTYxNTcyNzI0Mw==|d20ad0d1e62d84b00a3e74ec201a5917e77b6aef"`

`testuser|DIXXXXXXXXXXXXXXXXXX|1615727243`

1615727243  - expired 3 days ago

**Comment by xdesai** [comment]
The future is now! 😎 
Thanks for raising this. We'll take a look!
