### ISSUE TITLE
Python library not compatible with HMAC, Base64 in Python 3.4

### ISSUE THREAD

**Issue by cricalix** [duosecurity/duo_python#8]
When attempting to use the library in a Python 3.4 environment, the _sign_request() function will always return ERR_UNKNOWN. This comes down to the _sign_vals() function passing str objects to the underlying functions, instead of byte objects.

Underlying errors include:
TypeError: 'str' does not support the buffer interface
TypeError: Unicode-objects must be encoded before hashing

Re-writing _sign_vals() to look like this:

    def _sign_vals(key, vals, prefix, expire):
      exp = str(int(time.time()) + expire)

      val = '|'.join(vals + [ exp ])
      b64 = base64.b64encode(str.encode(val))
      cookie = '%s|%s' % (prefix, bytes.decode(b64))

      sig = _hmac_sha1(str.encode(key), str.encode(cookie))
      return '%s|%s' % (cookie, sig)

works just fine in Python 3.4, and in manual testing of the same functions in 2.7.

**Comment by mschwager** [comment]
Thanks for the heads up! It looks like there's a PR open for this issue (https://github.com/duosecurity/duo_python/pull/5). Does that code work for you? If so, we can work on accepting the PR :)

**Comment by cricalix** [comment]
Yes, that PR works just fine as well.

**Comment by cricalix** [comment]
Well, almost fine. The line about "user, ikey, exp = decoded.split('|')" in _parse_vals should be "user, u_ikey, exp = decoded.split('|')".

**Comment by mschwager** [comment]
https://github.com/duosecurity/duo_python/pull/9 should work for Python 3.3+

Let me know if you have any further issues! :)
